apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: quorum-node-metrics-exporter
  name: quorum-node-metrics-exporter
  namespace: epi-poc-quorum-metrics
data:
  # The config.
  # Required attributes: "rpc_url" and "peers"
  # - "rpc_url" = The full URL of the RPC endpoint of the quorum node, e.g. "http://quorum-node-0-rpc.quorum:8545"
  # - "peers" = A list of all known peers via their "enode".#
  #             "peers" contains an array of objects. Each object must have attributes "company-name" and "enode".
  #             Note: If there are no known peers, provide an empty array/list of peers.
  config.json: |-
    {
      "rpc_url": "http://quorum-node-0-rpc.epi-poc-quorum:8545",
      "peers": [
        {
          "company-name": "company_a",
          "enode": "4312d5056db7edf8b6..."
        },
        {
          "company-name": "company_a",
          "enode": "a36ceb6ccdf5ff8a7c..."
        },
        {
          "company-name": "company_a",
          "enode": "4801af270f75e9352b..."
        },
        {
          "company-name": "company_a",
          "enode": "456a860cb1275dd23..."
        },
        {
          "company-name": "company_b",
          "enode": "bc03e0353fe10d0261..."
        },
        {
          "company-name": "company_c",
          "enode": "b06bca847a8c27e7d..."
        },
      ]
    }