apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: quorum-node-metrics-exporter
  namespace: epi-poc-quorum
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list","get"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    # https://github.com/kubernetes-client/python/issues/690
    verbs: ["create","watch", "get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: quorum-node-metrics-exporter
  namespace: epi-poc-quorum
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: quorum-node-metrics-exporter
subjects:
- kind: ServiceAccount
  name: quorum-node-metrics-exporter
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: quorum-node-metrics-exporter
  namespace: epi-poc-quorum
---
